---
title: "How to Apply"
editor: visual
---

# Eligibility for application to the PATH-GDS program:

PATH-GDS aims to recruit, train, and retain quantitative MS students in data science-focused biomedical and genomics research, with particular focus on individuals from traditionally underrepresented groups.

Our pathway program is designed for students who:

-   Apply to the MS in Statistics or Applied Mathematics degree programs at the University of Colorado Denver.
-   Have interest in genetics and genomics.
-   Are a US citizen or permanent resident.

Please note that most coursework will be at CU Denver’s Downtown Campus and most rotations are offered at the CU Anschutz Medical Campus.

We encourage you to apply to the program even if you don’t have experience in genetics or genomics as long as you have interest in applying data science to biomedical, genetics, and genomics research.

We particularly encourage you to apply if you identify as a member of an underrepresented group (e.g., related to race, disability, gender, disadvantaged background, etc.).

# General requirement

### Intention to enroll into a Master Program

In order to be considered for the PATH-GDS program, interested students need to first apply to either the Master's program in Statistics or Applied Mathematics at CU Denver.

The links below provide additional information related to requirements, deadline, program details, etc.:

-   University of Colorado Denver, [MS in Applied Math](https://clas.ucdenver.edu/mathematical-and-statistical-sciences/master-science-applied-mathematics)
-   University of Colorado Denver, [MS in Statistics](https://clas.ucdenver.edu/mathematical-and-statistical-sciences/master-science-statistics)

If you are ready to start your MS Application, click [**BEGIN APPLICATION**]{.underline} in the following link:\
[LINK TO CU DENVER GRADUATE APPLICATION](https://clas.ucdenver.edu/mathematical-and-statistical-sciences/prospective-students)

In your application, respond "YES" to the question: **Are you interested in applying for the fully funded PATH-GDS Fellowship Program?**

Then, submit your [*written supplement*]{.underline} in the space provided.

### Written supplement

You should be ready to provide a 500-1000 words statement answering the following questions:

-   Why are you interested in learning about data science and genomics?
-   What do you hope to do after graduating from the program?
-   What obstacles have shaped who you are today? (This could be related to your socio-economic background, your identity, your values, your health, etc.)
