---
title: "Frequently asked questions"
sidebar: false
---

### How can I apply?

Please see the [Apply](https://hendricks-research-team.github.io/PATHGDS/Apply.html) section of our website.

### Can international undergraduate students who currently study in the USA participate in PATH-GDS?

Unfortunately, no. PATH-GDS scholars must be U.S. citizens or permanent residents.

### Can non-Colorado/non-WICHE students apply?

Yes! The program can only pay for in-state/WICHE tuition costs, but out-of-state students can pay the difference between in-state and out-of-state tuition during their first year. Students who plan ahead may be able to establish Colorado residency for tuition purposes prior to their second year in the program.

### Are there any program requirements related to minimum GPA, language tests, etc.?

Applicants must meet the requirements for admission to the [MS in Statistics](https://clas.ucdenver.edu/mathematical-and-statistical-sciences/master-science-statistics) or [MS in Applied Mathematics](https://clas.ucdenver.edu/mathematical-and-statistical-sciences/master-science-applied-mathematics). However, please let us know if you do not meet one of these requirements, as we may be able to work with you.

### Is there a separate application for admission?

There are additional PATH-GDS specific questions within the Statistics and Applied Mathematics MS applications. More information can be found in the [Apply](https://hendricks-research-team.github.io/PATHGDS/Apply.html) section of our website.

### Will this opportunity be available in the future?

Yes, we plan to have PATH-GDS scholars start in Fall 2027 and 2028.

### I’m currently a junior at CU Denver. Is this a program I can apply to as part of the 4+1 MS Stats degree? Or will it be available for me to apply to next year?

Yes, you can apply for this program as a junior. Please contact Joshua French for more information.

### Is the program in person or virtual?

This program is in person.

### Is there any specific focus outside of data science and genomics?

A student’s research should lie at the intersection of data science and genomics.

### Will the cost of relocation be paid for out-of-state students?

Relocation costs to Colorado are not covered.

### Is this only for master’s students? I’m an undergraduate, but I’m very interested in applying for the program.

This program is for people who would like to earn an MS in Statistics or Applied Mathematics. We recommend that undergraduates apply during the year they plan to graduate.

### How will the students be selected for the program?

Students are initially selected based on their admission to either the Statistics or Applied Mathematics MS program and their responses to the additional questions for the PATH-GDS program. We will then conduct supplemental virtual interviews with the top applicants before making our offers.

### I would like to know more about the laboratory-based research activity.

Scholars complete three 200-hour rotations with faculty at the Downtown or Anschutz Medical Campus. At least one rotation is in a wet lab (think lab coats, pipettes, and microscopes), and at least one rotation is in a dry lab (think working on a computer). The research within each lab depends on the interests of the faculty mentor. Some examples include Type 1 diabetes research, genetics of nutrition and taste, identifying substructure in genomic summary data, methods to maintain genomic privacy, genetic risk score modeling, single-cell genomics, machine learning, and AI prediction models.

### Is it OK to apply if you don’t have a background in genomics? What science backgrounds are you looking for?

Absolutely! This program is designed to provide experience in genomics. No science background is needed. However, a background in mathematics or statistics sufficient to meet the MS admission requirements in Applied Mathematics or Statistics is needed. We are looking for people who are interested in learning more about genomics research.

### Is there an ethics component to the degree plan?

Yes, there is a required ethics course that scholars take in their first year. Additionally, we provide ethics-related training as part of our monthly seminars.

### Is there a specific deadline for applications, and is admission rolling or determined after the deadline?

The deadline for full consideration is February 22. After the deadline, applications are considered on a rolling basis as space is available.

### I'd like to know more about specific coursework, day-to-day life, and what kind of expectations PATH-GDS has for applicants.

Students will complete the standard coursework for the Statistics or Applied Mathematics programs at CU Denver. Three electives will be PATH-GDS-specific. The program requirements for the Statistics MS are available [here](https://clas.ucdenver.edu/mathematical-and-statistical-sciences/degree-requirements-ms-statistics), and the requirements for the Applied Mathematics MS are available [here](https://clas.ucdenver.edu/mathematical-and-statistical-sciences/degree-requirements-ms-applied-mathematics).

Day to day, students will attend classes and/or participate in their lab rotations. Students typically try to arrange their schedules so that they only have classes two days per week and can focus on their lab rotations and other responsibilities on the other days.

We expect students to work hard, ask questions, and learn a lot.

### I have never done a research study. What do I need to know beforehand?

Nothing. We will train you in these kinds of skills during orientation, professional development seminars, and your lab rotations.

### Can you elaborate on what it means for scholars to have mentorship opportunities as both a mentee and mentor?

This program employs near-peer mentoring. You will be mentored by the directors, lab directors, PhD students, and second-year students. You will, in turn, mentor undergraduate students in a similar program. We will prepare you to do this successfully.

### What specific skills and experiences do students gain through the PATH-GDS program's coursework, laboratory rotations, and professional development opportunities, and how do these prepare them for careers in academia or industry?

Students will learn the mathematical and statistical skills needed to complete their degree programs, receive training in genomics and ethics, and gain hands-on research experience in several labs. Students are able to select labs that are most compatible with their interests and goals. Professional development focuses on topics such as networking, preparing an abstract, giving a scientific presentation, and creating a professional website, as well as training in diversity and inclusion. These skills are valuable in both academia and industry.

### What exactly does fully funded mean?

Please see the [Overview](https://hendricks-research-team.github.io/PATHGDS/overview.html) page of our website. In summary, we will pay for 30 credits of in-state/WICHE tuition (enough to earn an MS), student fees, provide a health insurance stipend, and provide a monthly salary for lab work (about $1,800 per month).

### Is the master's fully funded as well, or only the fellowship program? Is the master's required to complete the fellowship program?

The MS and fellowship go hand in hand. Scholars must complete the MS as part of the fellowship and are fully funded while doing so.
