---
title: ""
---

::: whitebox
::: {style="padding-left: 10px; padding-right: 10px; display: inline-block;"}
::: {style="text-align: left;"}
# What is PATH-GDS?

PATH-GDS is a two-year program to introduce and train CU Denver MS Statistics and MS Applied Mathematics students in genomics research. 

Our inclusive and extensive training program builds academic and industry genomics pathways for genomics data scientists by:

-   Training the scholars through coursework and rotations in genomics research

-   Immersing scholars in a 17-month laboratory experience

-   Exposing scholars to Genomic professional development through didactic seminars, panels, and workshops.

-   Preparing Scholars for future career through soft skills training: research communication, Guidance for application in doctoral programs and industry positions

-   Providing A strong community to help build scholars' identities as genomic data scientists
:::
:::
:::

::: whitebox
::: {style="padding-left: 10px; padding-right: 10px; display: inline-block;"}
::: {style="text-align: left;"}
# What you will gain by being a PATH-GDS scholar:

PATH-GDS offers resources to support its scholars throughout the pathway program:

-   Successful students will earn an MS in Statistics or Applied Mathematics in two years.

-   Coursework through the program includes 3 genomics research-related electives (including a course on ethics in biomedical research).

-   Students will attend seminars and workshops in genomics, research, and professional skills Funding provided: \$25/hour for 15 hours of research during the academic year and 40 hrs/week during the summer

-   In-state tuition (up to 15 credits per year), fees, and healthcare insurance (up to $1350 per semester) are covered by the program.

-   Students will have the opportunity to attend a local or national conference Students will participate in rotations and research experiences in wet (laboratory based) and dry (computational) genomics labs

-   Students will gain mentorship experience as both the mentee and mentor
:::
:::
:::

If you would like to attend the information session (Nov 8 or Nov 9) or have any question about the program, please fill in the following [Interest form](https://forms.office.com/r/kLQw9QuD5n)

::: whitebox
::: {style="padding-left: 10px; padding-right: 10px; display: inline-block;"}
::: {style="text-align: left;"}
# Program timeline 2024-2025:

+---------------------------------+--------------------------------------+
| Date\                           | Event                                |
| *( Exact date will be updated)* |                                      |
+=================================+======================================+
| **Mid March 2024**              | Acceptance into the program          |
+---------------------------------+--------------------------------------+
| **May 2024**                    | PATH-GDS Retreat                     |
+---------------------------------+--------------------------------------+
| **Beginning August 2024**       | Orientation week                     |
+---------------------------------+--------------------------------------+
| **Mid August 2024**             | -   MS classes start (Year 1)        |
|                                 | -   First 8-week lab rotation        |
+---------------------------------+--------------------------------------+
| **Mid October 2024**            | Second 8-week lab rotation           |
+---------------------------------+--------------------------------------+
| **Beginning January 2025**      | Third 8-week lab rotation            |
+---------------------------------+--------------------------------------+
| **Mid February 2025**           | Start of 17 month lab experience     |
+---------------------------------+--------------------------------------+
| **Mid May 2025**                | End of MS Year 1                     |
+---------------------------------+--------------------------------------+
:::
:::
:::
